-- 1. Tabla de Alumnos
CREATE TABLE ALUMNOS (
    ID_ALUMNO INTEGER PRIMARY KEY,
    NOMBRE TEXT,
    APELLIDO TEXT,
    CEDULA TEXT
);
-- 2. Tabla de Profesores
CREATE TABLE PROFESORES (
    ID_PROFESOR INTEGER PRIMARY KEY,
    NOMBRE TEXT,
    ESPECIALIDAD TEXT
);
-- 3. Tabla de Materias
CREATE TABLE MATERIAS (
    ID_MATERIA INTEGER PRIMARY KEY,
    NOMBRE_MATERIA TEXT
);
-- 4. Tabla de Secciones (Conecta Profesores y Materias)
CREATE TABLE SECCIONES (
    ID_SECCION INTEGER PRIMARY KEY,
    ID_PROFESOR_FK INTEGER,
    ID_MATERIA_FK INTEGER,
    AULA TEXT,
    HORARIO TEXT,
    FOREIGN KEY (ID_PROFESOR_FK) REFERENCES PROFESORES(ID_PROFESOR),
    FOREIGN KEY (ID_MATERIA_FK) REFERENCES MATERIAS(ID_MATERIA)
);
-- 5. Tabla de Inscripciones (Conecta Alumnos con Secciones)
CREATE TABLE INSCRIPCIONES (
    ID_INSCRIPCION INTEGER PRIMARY KEY,
    ID_ALUMNO_FK INTEGER,
    ID_SECCION_FK INTEGER,
    FECHA TEXT,
    FOREIGN KEY (ID_ALUMNO_FK) REFERENCES ALUMNOS(ID_ALUMNO),
    FOREIGN KEY (ID_SECCION_FK) REFERENCES SECCIONES(ID_SECCION)
);